services:
  - type: web
    name: drowk-backend
    env: node
    plan: starter
    rootDir: backend
    buildCommand: npm install
    startCommand: npm run start
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: REQUIRE_API_TOKEN
        value: true
      - key: PORT
        value: 10000
      - key: CORS_ORIGINS
        sync: false
      - key: INTERNAL_API_TOKEN
        sync: false
